[package]
name = "codegen"
version = "1.0.0"
authors = ["Jakub Syty <jakub.syty@euvic.pl>"]
edition = "2018"

[lib]
crate-type=["rlib", "cdylib"]

[dependencies]
byteorder = "~1.3.2"
ole32-sys = "0.2.0"